scipion-em/scipion-em-tomo

tomo/protocols/__init__.py
tomo/protocols/protocol_base.py

Create a base boxing class for tomography.
To see how an example of how this class is being used see https://github.com/scipion-em/scipion-em-eman2/pull/20

Add base tomo boxing class

---

tomo/objects.py
tomo/protocols/__init__.py
tomo/protocols/protocol_base.py

See https://github.com/scipion-em/scipion-em-eman2/pull/22 for an example of use

Changes for extract subtomogram protocol

---

tomo/objects.py
tomo/protocols/__init__.py
tomo/protocols/protocol_import_subtomograms.py
tomo/protocols/protocol_import_tomograms.py
tomo/viewers/viewer_tomograms.py

- Import Subtomograms and modify protocol viewer
- Fixes all comment from previous PR https://github.com/scipion-em/scipion-em-tomo/pull/1#discussion_r271166538
- Extend SetOfSubtomograms

[WIP] Import subtomograms

---

tomo/__init__.py
tomo/protocols/__init__.py
tomo/protocols/protocol_base.py
tomo/viewers/viewer_tomograms.py

Re https://github.com/I2PC/scipion/issues/2036, @pconesa and I implemented this quick fix that seems to fix the problem. Thoughts @delarosatrevin? Too hacky?

tentative fix for subset for tomo and subtomo

---

.gitignore
tomo/protocols/protocol_ts_import.py

worksIsStreaming must be a class method

---

tomo/convert/__init__.py
tomo/objects.py
tomo/protocols/protocol_import_subtomograms.py
tomo/protocols/protocol_import_tomograms.py
tomo/protocols/protocol_ts_correct_motion.py
tomo/protocols/protocol_ts_estimate_ctf.py
tomo/protocols/protocol_ts_import.py

Merge features into one single branch (fi_feature_fiducialModel) for merging into python3_migration

Fi feature ts methods

---

tomo/objects.py
tomo/protocols/protocol_base.py
tomo/protocols/protocol_import_coordinates.py
tomo/viewers/viewers_data.py
tomo/viewers/views_tkinter_tree.py

Several changes included:
- Modification of `TomogramsTreeProvider` to allow the handling of .txt and .json files.
- Addition of `MeshesTreeProvider` and modification of `TomogramsDialog` that allows to generate GUI for objects of type `SetOfMeshes`.
- New structure for the object `Mesh` to simplify its usage (including a new group attribute to differentiate different meshes belonging to the same Tomogram).

Dh eman gui

---

tomo/objects.py
tomo/protocols/protocol_import_coordinates.py
tomo/tests/test_tomo_base.py
tomo/viewers/views_tkinter_tree.py

- Mofication of Import Coordinates 3D to include the possibility of importing tables from Dynamo
- The object `Coordinate3D` stores a Transormation Matrix. The main purpose is to include directionality to the coordinate as required by some softwares such as Dynamo
- Migration of the code to be comptaible with Scipion3
In order to import from Dynamo table files, the following [branch](https://github.com/scipion-em/scipion-em-dynamo/pull/7) from scipion-em-dynamo is required.

Dh directionality

---

tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_alignment_assign_subtomo.py
tomo/tests/test_tomo_base.py

Protocol to assign alignment (transformation matrix) from a `SetOfSubtomograms` to another `SetOfSubtomograms`. This protocol is based on protocol [https://github.com/scipion-em/scipion-em/blob/devel/pwem/protocols/protocol_alignment_assign.py](url) for SPA.

assign alignment subtomo

---

tomo/protocols/protocol_extract_coordinates.py

Added the possiblity of linking the subtomograms and the tomograms by their file names when the object ID is not avalaible.

Fixes for protocol_extract_coordinates

---

tomo/objects.py

- Minor changes in TiltSeries object applyTransform method

fixes in output tilt-series sizes in apply transform method

---

tomo/objects.py
tomo/protocols/protocol_ts_import.py

- Add examples to import tilt-series help to fix #62 
- Capture {TS} error
- Add guidelines for {TS} field
- New method in tilt-series object to parse the filename

Fi fixes import ts

---

tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_consensus_classes_subtomo.py

New protocol to do consensus of Classes of subtomograms (analogous to xmipp3 - consensus classes 3D)

Consensus classes subtomo

---

tomo/protocols/protocol_extract_coordinates.py
tomo/protocols/protocol_import_coordinates.py
tomo/protocols/protocol_import_subtomograms.py
tomo/protocols/protocol_import_tomograms.py

Added _validate method to imports and extract coordinates protocols in order to avoid getting empty sets in the output

Validate added to some protocols

---

tomo/protocols/protocol_import_coordinates.py
tomo/protocols/protocol_import_tomograms.py

Some imports has been modified in order to work properly with the new emantomo plugin.

Fixed import coordinates from Eman

---

tomo/objects.py

- New method to retrieve landmark information as a table

add new method to landmarmodel onject to generate imod fiducial files

---

tomo/objects.py

- Fixes in ctf tomo series for propely db connection closing

fixes in ctf series for propely db connection closing

---

tomo/objects.py
tomo/protocols/protocol_assignTransformationTS.py

- Add clone method to CTF tomo series object
- Update email in assign transformation TS

Fi fixes clone ctf series

---

tomo/convert/__init__.py
tomo/convert/convert.py
tomo/protocols/protocol_import_coordinates.py
tomo/tests/test_tomo_base.py
tomo/utils.py

Import coordinates protocol has been modified to dynamically detect if a Plugin involved in the import (currently Dynamo or Eman) is installed and to modify the import choices offered to the user accordingly.

Dynamic choices in import coordinates 3D

---

tomo/objects.py

- Changes in ts.applyTransform: substitute createAbsLink for createLink -> failing when working with ts from input

change createAbsLink for createLink 

---

tomo/objects.py

- New copy info method in CTFTomo object
- New getters, setters, and checkers in both CTFTomo and CTFTomoSeries objects

Complete CTF tomo model

---

tomo/objects.py
tomo/protocols/protocol_ts_estimate_ctf.py

- the output now is a CTFTomo object
- the protocol input can be SetOfTiltSeries or SetOfCTFTomoSeries

* Refactoring ts_estimate_ctf

---

tomo/viewers/views_tkinter_tree.py

move index to path, move order to TS column

---

tomo/protocols/protocol_ts_correct_motion.py
tomo/protocols/protocol_ts_estimate_ctf.py
tomo/tests/test_import.py
tomo/tests/test_tomo_base.py
tomo/viewers/viewers_data.py
tomo/viewers/views_tkinter_tree.py

fix output sampling rate

---

tomo/objects.py
tomo/tests/test_tomo_base.py

* Copying the info including _anglesCount from other set
* Fixing a test error creating  subsets

* Copying the info including _anglesCount from other set

---

tomo/objects.py

- Fixes in SetOfTiltSeriesBase iterItem()
- Add TiltSeries attribute to LandmarkModel class, getters and setters
- Complete SetOfLandmarkModels class with methods to handle the new attribute in item class

Fi feature complete lm

---

tomo/protocols/__init__.py
tomo/protocols/protocol_ctf_validate.py
tomo/viewers/viewer_tomograms.py
tomo/viewers/views_tkinter_tree.py

* Creating a protocol to validate a set of ctf tomo series(classify in good or bad ctf series)
* ViewerProtImportTomograms deprecate (we need to determine if remove it)
* Validating the acquisition values

* Creating a protocol to validate a set of ctf tomo series

---

tomo/protocols/protocol_split_evenodd_subtomos.py
tomo/viewers/__init__.py
tomo/viewers/viewer_split_evenodd.py

The implementation of this viewer solves issue https://github.com/I2PC/scipion-em-xmipptomo/issues/57

viewer for split even/odd

---

tomo/viewers/views_tkinter_tree.py

This PR updates workshop with devel (fixes in ctf viewer)

Update workshop with devel

---

tomo/protocols/protocol_ts_correct_motion.py
tomo/viewers/viewers_data.py

TS motion correction now outputs DW TS if supported by child protocols. Viewer updated

add DW support for mc

---

tomo/objects.py
tomo/protocols/protocol_import_subtomograms.py
tomo/protocols/protocol_ts_import.py
tomo/tests/test_tomo_base.py

this centrailize the handling of the origin function in the Coordinate3D object
Also: fix a error in validateAngles in the import tilt series

Refactor coordinate3d

---

tomo/objects.py
tomo/utils.py

* Adding some methods to write artificial etomo files
* Adding a method to recover a TS with the transform matrix navigating through the workflow

* Adding some methods to write artificial etomo files

---

tomo/objects.py

- Add logic to apply transformation matrix in tilt series object to swap x and y dimensions
- Refactor tomo objects (via pycharm)

Swap XY dim logic to TS apply transofrmation matrix

---

tomo/objects.py
tomo/tests/test_objects.py
tomo/viewers/__init__.py
tomo/viewers/viewers_data.py

Coordinates3dDataViewer renamed since now it can visualize new object, SetOfMeshes, SetOfLandmarkModels

New object for tilt series coordinates and its test.

---

tomo/objects.py

Fixes in tilt series coordinates object

Fixes in tilt series coordinates object

---

tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_ts_convert_coords3d.py

- New protocol to convert tilt series coordinates to tomo coordinates 3d
- Add protocol to init and protocols conf.

Convert tilt series coordinates 3d to tomo coordinates 3d

---

tomo/protocols.conf

fix missing coma

---

tomo/objects.py
tomo/tests/test_objects.py

This provides some 2 methods in SetOfTomogrmas and SetOfCoordinates3D to iterate over those tomograms actually present in the contained items

Constants and set methods

---

tomo/protocols/protocol_ts_correct_motion.py

For motion correction base protocol

add possible outputs

---

tomo/convert/mdoc.py
tomo/objects.py
tomo/tests/test_import.py
tomo/tests/test_objects.py

Fix SOST.getTomogram() (do not use vol id)

---

tomo/objects.py
tomo/protocols/protocol_base.py

accumDose is only copied by TS as part of the acquisition attr from the first item. It has to be updated for each tilt image.

close #196

---

tomo/protocols/protocol_tomo_to_mics.py

This should fix an error cause mics generated were missing the acquisition info

Fix tomo to mics

---

tomo/protocols/protocol_ts_consensus_alignment.py

- Modification of consensus alignment to allow local analysis.

Extend consensus alignment to local analysis

---

tomo/objects.py

getters and setters uses directly the internal instances

Landmark has size now (defults to 5 px)

---

tomo/convert/mdoc.py
tomo/protocols/protocol_ts_import.py
tomo/tests/test_import.py

improve help and validation messages

---

tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_misalignTS.py

Add misalign tilt series protocol and remove it to sicpion-em-xmipptomo. This PR depends on https://github.com/I2PC/scipion-em-xmipptomo/compare/fi_remove_misali_TS?expand=1

Fi add misali ts

---

tomo/objects.py

* Formatting 3d coordinates in order to be used to compare them in different pseudosubtomograms

* Formatting 3d coordinates

---

tomo/tests/__init__.py

update test dataset

---

tomo/objects.py

* Adding the append method in SetOfCoordinate3D in order to set the boxsize(taking into account the Coordinate3D) if is None

  * Adding the append method in SetOfCoordinate3D

---

CHANGES.txt
tomo/convert/convert.py
tomo/objects.py
tomo/protocols/protocol_import_coordinates.py
tomo/tests/test_import.py

Allowing shift per axis in import coordinates

Import cbox

---

tomo/protocols/protocol_ts_correct_motion.py

Closes #343
setIndex is not necessary as it's done by setLocation

fix DW TS output from motion correction

---

tomo/protocols/protocol_compose_TS.py
tomo/tests/test_compose_TS.py

- Better information provided
- Removed a unnecessary parameter (time2NextMic), because now is checked the stream status of the set of mics.
- Improved the managed of list of mdocs available
Related to [issue](https://github.com/scipion-em/scipion-em-tomo/issues/353)

ComoseTS: improves and fixes

---

CHANGES.txt
tomo/protocols/protocol_compose_TS.py

- allowNull control added
- Removed validation (you 'd like to run the protocol without micrograps in the setOfMicrographs)
- Text clarification

ComposeTS: possibleOutputs

---

CHANGES.txt
tomo/__init__.py

- Relion 4 /dynamo  template tweaked. Specifically dynamo alignment

  - Reconstruction template fixed.

---

tomo/protocols/protocol_compose_TS.py

Compose TS

---

CHANGES.txt
tomo/convert/__init__.py
tomo/protocols/protocol_ts_import.py

- Tolerate empty lines in tlt files

---

tomo/objects.py

- Changes in LandmarkModel object to save if it has residual information

Add hasResidualInfo parameter to Landmark models

---

CHANGES.txt
README.rst
tomo/__init__.py
tomo/constants.py
tomo/viewers/viewers_data.py
tomo/viewers/views_tkinter_tree.py

As discussed earlier, the binary installation is now here

centralize napari binary installation and config var

---

tomo/protocols/protocol_assignTransformationTS.py

- Enhancement of tilt series assign alignment protocol. Now we make the intersection of the two sets plus allow the combination of alignments.

Fi improve ts assign tm

---

tomo/protocols/protocol_misalignTS.py
tomo/protocols/protocol_ts_convert_coords3d.py

- Improvements in the misalign TS protocol

Fi improve misali ts

---

tomo/protocols/protocol_compose_TS.py

- Allowed Tilt series with gaps just in case the set of micrographs is closed, else the tilt serie waits to full fill
- Moved to extra some files
- Lazy and simpler summary

Allowing tilt series with gaps

---

requirements.txt

segmentation to mesh needs mrcfile 1.4+

---

CHANGES.txt
tomo/__init__.py
tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_import_ctf.py

Similar to SPA, the idea is to have one import CTF protocol that will call the code from different plugins.
Related PRs: 
https://github.com/scipion-em/scipion-em-cistem/pull/74
https://github.com/scipion-em/scipion-em-imod/pull/243

add common ctf import protocol

---

CHANGES.txt
tomo/viewers/views_tkinter_tree.py

- Taking a central tiltimage if a tiltserie is selected
-  Asking if you want to close having made changes

  - Asking if you want to close having made changes and Taking a central tiltimage if a tiltserie is selected

---

CHANGES.txt
tomo/__init__.py
tomo/objects.py
tomo/protocols/protocol_ts_import.py

closes #334
Compared to SPA, this is only set on a movies set, not per each movie.

setFramesFrange when importing TS movies

---

tomo/viewers/views_tkinter_tree.py

I implemented a new method for increasing contrast when pressing the button, that just truncates the pixel values to +/- n-times the standard deviation around the mean.
The constant `CONTRAST_STD` controls how many standard deviations to truncate (default is 0.5).
This way, no `skimage` dependency is needed anymore.

Changed method of increasing contrast

---

CHANGES.txt
tomo/viewers/views_tkinter_tree.py

- Fixing an error creating new outputs through the tiltserie viewer. 
- Fixing an error plotting the defocus values in the ctfEstimation viewer

Fixing the TS and CTFEstimation viewers

---

CHANGES.txt
tomo/__init__.py
tomo/viewers/views_tkinter_tree.py

Adding angles and the transformation matrix information

Adding angles and the transformation matrix information

---

CHANGES.txt
tomo/__init__.py
tomo/constants.py
tomo/objects.py
tomo/protocols/protocol_compose_TS.py

- Fixing an error in the compose_TS protocol creating the TS
- Using the getSize method to get the anglesCount

- Fixing an error in the compose_TS protocol creating the TS

---

CHANGES.txt
README.rst
tomo/protocols.conf
tomo/protocols/__init__.py
tomo/protocols/protocol_export_coords.py
tomo/tests/test_export.py

closes #539 
There seem to be two problems:
1) exported cbox coordinates do not match the imported cbox one - @fonsecareyna82 please help :)
2) dynamo matrix2eulerAngles(coord.getMatrix()) does not match the input tbl values - I've commented out the code for now
Feel free to improve the tests If necessary

add export coords 3d protocol

---

tomo/protocols/__init__.py
tomo/protocols/protocol_project_coordinates.py

This small protocol allows to project 3D coordinates into a tilt series for visualization purposes.

Protocol to project 3D coordinates into landmarks

---

tomo/protocols/protocol_mesh_from_segmentation.py

Refactored `meshes from tomo mask protocol` to run in semi-streaming fashion. In addition added an optional skeletonization preprocessing to the input masks to enhance the quality of the output meshes. Nevertheless this process is computationally expensive.

Refactored meshes from tomo mask protocol and added optional skeletonization step
