scipion-em/scipion-em-tomo

tomo/protocols/protocol_ts_import.py
These changes allow the imported from range angles to be in the opposite order so they fit the tilt series stack.
=> Small import changes

tomo/objects.py, tomo/protocols.conf, tomo/protocols/__init__.py, tomo/protocols/protocol_import_coordinates.py, tomo/tests/test_tomo_base.py
-Attribute **samplingRate** added to object `SetOfCoordinates3D` with the corresponding get and set.
-In `protocol_import_coordinates` set samplingRate of object SetOfCoordinates3D
This changes are required for the correct working of `protocol_tomo_extraction` in `scipion-em-eman2` after PR scipion-em/scipion-em-eman2/pull/33
*Extra: **Remove non-tomography imports** from `protocols.conf` by user request (they have no sense in tomography menu of scipion and they are confusing for the user).
=> Add sampling rate to SetOfCoordinates3D

tomo/protocols.conf, tomo/protocols/protocol_ts_correct_motion.py
Fix protocols.conf to show correctly currents sections in Tomography menu of Scipion.
I have added to those sections the protocols regarding tilt series (import tilt series, import tilt series movies and average tilt series). Please @delarosatrevin check if they are located in the correct section and if I missed include any "user" protocol (**not** base protocols) in protocols.conf.
=> add ts protocols to protocols.conf

tomo/protocols/protocol_import_subtomograms.py, tomo/tests/__init__.py, tomo/tests/test_tomo_base.py
Now it is possible to import subtomograms from dynamo (importing the metadata from dynamo tables).
To use this new feature it is necessary to have installed the dynamo plugin (https://github.com/scipion-em/scipion-em-dynamo) in branch https://github.com/scipion-em/scipion-em-dynamo/pull/3 (in PR now).
However, the basic import should be work without dynamo.
=> Import dynamo subtomos

tomo/protocols/__init__.py, tomo/viewers/views_tkinter_tree.py
Small fix to solve the error showing when Tomograms with no `SetOfMeshes` associated were opened with ImageJ.
=> Error showing when opening Tomograms with no meshes in viewer fixed

tomo/protocols/protocol_ts_estimate_ctf.py
This PR goes together with https://github.com/scipion-em/scipion-em-gctf/pull/22 and https://github.com/scipion-em/scipion-em-cistem/pull/11.
In gctf / grigoriefflab repos the tomo+python3 branches created by @delarosatrevin were quite outdated from the current code in gctf/cistem, specifically GUI forms have changed a lot. This PR introduces the following changes:
1) move all GUI params to subclasses (gctf/cistem protocols)
2) both gctf and cistem/ctffind use defocus in Angstroms, no need to convert from microns anymore.
3) add missing getCtf func definition in the base class
=> refactor base ctf protocol

tomo/objects.py, tomo/protocols.conf, tomo/protocols/__init__.py, tomo/protocols/protocol_extract_coordinates.py, tomo/tests/test_tomo_base.py
`protocol_extract_coordinates` added to Tomo plugin. It extracts the coordinates associated to a `SetOfSubTomograms` and outputs them after being linked them to a new `SetOfTomograms`.
=> Extract coordinates for tomo

tomo/objects.py
Method `__getitem__` from objects `SetOfCoordinates3D` and `SetOfMeshes` has been modified to link the Tomograms that were lost when generating the sqlite files.
The method `iterCoordinates` and `iterItems` from these two objects has been also modified accordingly to overcome the issue.
=> New __getitem__ method

tomo/protocols/protocol_import_subtomograms.py, tomo/tests/test_tomo_base.py
`Input coordinates `functionality commented in` input subtomograms protocol`, as it is not working properly for the moment. It was assigning a coordinate to a subtomogram in consecutive order without ensuring that the coordinate really belong to that subtomogram. 
In the case of importing subtomograms from Dynamo, this functionality has no sense anyway because coordinate information of the subtomogram is already contained in the Dynamo table (metadata).
The code is commented instead of removed to keep it for a future fix of this functionality.
=> remove coordinates in import subtomograms

tomo/protocols.conf, tomo/protocols/__init__.py, tomo/protocols/protocol_assign_tomo2subtomo.py, tomo/tests/test_tomo_base.py
New protocol to assign a set of tomograms to a set of subtomograms that have been imported to Scipion before without being related with any tomograms.
Subtomograms should contain in their own filename the name of the original tomogram from wich the subtomogram was extracted.
=> Assign tomos2subtomos

tomo/protocols/protocol_import_subtomograms.py, tomo/tests/test_tomo_base.py
Remove from `protocol_import_subtomograms` the option `from Dynamo` (and test) in order to avoid dependencies, as agreeded. Now, the impor subtomograms from dynamo protocol is in `scipion-em-dynamo` plugin (https://github.com/scipion-em/scipion-em-dynamo/pull/15).
=> move dynamo import to its plugin

tomo/tests/test_tomo_base.py
Removed `pattern` from the inputs provided when executing the subtomogram importer through its test to avoid errors in the path generation.
=> Fixed Import Subtomograms Test

tomo/viewers/__init__.py, tomo/viewers/viewer_tomograms.py
Modify the viewer so it can be used with chimerax (chimera is not longer supported by scipion). 
chimera visualization in devel was broken, I fixed it and then I updated it for chimeraX. Remember that  you will need to reinstall scipion-em-chimerax and the last version os scipion-em in order to run this PR.
=> update for chimerax

tomo/protocols.conf, tomo/protocols/__init__.py, tomo/protocols/protocol_assignTransformationTS.py
- New protocol to assign transformation matrices from one set of tilt-series to another
- Changes needed in init and protocols.conf
=> Fi feature assign transofrmation matrix to set of tilt series

tomo/protocols.conf, tomo/protocols/__init__.py, tomo/protocols/protocol_particle_pick_consensus.py, tomo/protocols/protocol_particle_pick_remove_duplicates.py, tomo/tests/test_tomo_base.py
Port of protocols `protocol_particle_pick_remove_duplicates` and `protocol_particle_pick_consensus` from Xmipp to work with Tomo objects `SetOfCoordinates3D` and `Coordinate3D`.
Together with the protocols a couple of tests have been also included (`TestTomoPickingConsenus` and `TestTomoPickingRemoveDuplicates`).
=> Picking Consensus and Remove Duplicates

tomo/protocols/protocol_particle_pick_consensus.py, tomo/protocols/protocol_particle_pick_remove_duplicates.py, tomo/tests/__init__.py, tomo/tests/test_tomo_base.py
- Test for `protocol_particle_pick_consensus` has been extended to cover the different combination of the parameters.
- New functionality added to `protocol_particle_pick_consensus` and `protocol_particle_pick_remove_duplicates`. After finding new coordinates, a triangulation is generated to readjust the normals and the transformation matrices to the new coordinates. This functionality requires the changes from [#325](https://github.com/I2PC/scipion-em-xmipp/pull/325) to work properly. New dependency (pyvista) added to scipion-em-xmipp is also needed.
=> Consensus improved tests and normal adjustment

tomo/utils.py, tomo/viewers/viewers_data.py
The method `extractVesicles` from `utils.py` has been modified to load only those vesicles blonging to a specific Tomogram. Toghether with this functionality, a new method (`initDictVesicles`) has been added to initialize the dictionary to be used with the new version of `extractVesicles`.
The PR includes also a small fix for the viewer of `SetOfMeshes`.
=> Load Vesicles from Tomogram on demand

tomo/protocols/protocol_import_coordinates.py, tomo/protocols/protocol_import_subtomograms.py, tomo/protocols/protocol_import_tomograms.py
- Moved warning message (`protocol_import_coordinates`) to _warning method to avoid prints in the console.
- Modified `protocol_import_coordinates`, `protocol_import_subtomograms` and `protocol_import_tomograms` to avoid loading all input files when checking the input path pattern.
=> Warning Method and Checks

tomo/viewers/viewer_tomograms.py, tomo/viewers/viewers_data.py, tomo/viewers/views_tkinter_tree.py
Move viewer temporary files to extra path to avoid errors due to missing tmp path
=> Viewer temporary files moved to extra

tomo/protocols/protocol_assignTransformationTS.py
-  Fixes in assignTransformationTS protocol. Now output information is not messed up between both input sets.
=> Fi fixes assign alignment

tomo/viewers/__init__.py, tomo/viewers/viewers_data.py, tomo/viewers/views_tkinter_tree.py
- Tkinter  CtfEstimationListDialog and the CtfEstimationTreeProvider for SetOfCTFTomoSeries are moved from imod plugin
- CtfEstimationTomoViewer has plot1D and plot2D funcs that should be implemented in subclasses
- PSD plot added for child TS items
- 1D fit plot added for child TS items (click 1D fit button on the top)
- Defocus plot updated for parent TS items
- Only one defocus value is displayed (defocusU)
- Sorting the tree columns does not work for now
@fonsecareyna82 I need your help to get around creating subclasses. Now, e.g. cistem viewer has to have:
```
class CtfEstimationTomoViewerCistem(CtfEstimationTomoViewer):
def plot1D(self, ctfSet, ctfId):
...
def plot2D(self, ctfSet, ctfId):
...
```
This means that each plugin creates it's own viewer that gets registered. I can't …
=> working on tomo ctf viewer

tomo/objects.py, tomo/protocols/protocol_ts_correct_motion.py, tomo/protocols/protocol_ts_import.py, tomo/tests/test_import.py, tomo/viewers/views_tkinter_tree.py
- Expand TomoAcquisition with the accumulated dose. As a consequence, update importTS, import tests and TS viewer
- Method getVolumeOrigin raises an exception if not volume is associated to the current 3D coordinate, something which commonly happens when generating coordinates
- Voltage, magnification and sampling rate are not required in the case of mdoc, but if they're filled, they'll have higher priority than the values read
=> Jj ts import fixes

tomo/objects.py
- Add TM to copy info for Tilt-Series (TS, TSM, and TSBase). Needed to keep TM in subsets.
=> Add TM to copy info. Needed for subsets

tomo/protocols/protocol_ts_import.py
Hi,
The tomo data acquired using TALOS stores the tiltangle following the format
[T =   TiltAxisAngle = -91.81  Binning = 1  SpotSize = 7]
At present  sdcipion-em-tomo assumes a format as
and splits the string using "," as delimiter. This approach does not work with the Talos data.
We summit a new parsing approach that should be able to process both case
changes made in the code:
-                            tiltAxisAngle = strLine.split('tiltaxisangle=')[1].split(',')[0]
+                            # [T =   TiltAxisAngle = -91.81  Binning = 1  SpotSize = 7]
+                            tiltAxisAngle = strLine.split('=')[2].split('binning')[0]
=> update parsing of tiltAxisAngle so Talos data

tomo/tests/test_transformations.py
branch name is wrong. This just improves the tests results
=> do not average using missing wedge info in test

tomo/objects.py
This essentially reverts https://github.com/scipion-em/scipion-em-tomo/pull/115 so that scratch use is supported.
=> use abslink

tomo/objects.py
- Add setVolId call when setting the coordinate3D so it can be iterated
- Writing tilt.com files method admits now X and Y size given by a keyword. If not provided, these dimensions will be read from the TS
=> Jj update ctftomoseries iterator

tomo/convert/mdoc.py
this closes #232 
With the fix the TS below is imported correctly, the dose and acq order are correct:
=> sort mdoc Z-slices by datetime before import

tomo/objects.py
I dont expect thousands of averages, so I think we can afford this change. SetOfSubtomos still have expose=False which is okay
=> expose avg subtomos items for object viewer

tomo/objects.py
If a ts has excluded tilt images, their disabled status will be copied. This avoid the need to modify every single createoutputstep for many tomo protocols. Otherwise, disabled items from the input become enabled in the output.
=> copy enabled status for tilt images

tomo/objects.py
Representing the angles with a big number of decimals can make trouble. For example, if the emantomo TS alignment, the angles are refined and stored with a lot of decimals, that are then written in a tlt file before reconstructing with any other algorithm, like tomo3d. In that case, tomo3d interprets the number of angles as more than one angle each, taking the first n ones to reconstruct and obtaining a bad reconstruction.
On the other hand, I think that 3 (as proposed) or 4 decimal positions are more than enough in terms of angle precision.
=> Jj fix generate tlt file method

tomo/protocols/protocol_ts_convert_coords3d.py
- Fixes in convert tilt series coordinates to 3D coordinates when tomogram set does not completely contain the set of coordinates
=> Fix error when tomogram set does not completely contain the set of coordinates

tomo/protocols/protocol_compose_TS.py
With the change, areTomo creates the tomogram. 
Tested with real tilts in galileo-shadow (agarcia user)
=> ComposeTiltSeries: ObjID starts with 1 not 0

CHANGES.txt, tomo/convert/__init__.py, tomo/protocols/protocol_ts_import.py
In this PR I added the option (does not impact previous usage) to import the accumulated dose of a tilt series as a second column in the tlt/rawtlt file.
This is not a new practice, it is already allowed in the same way in aretomo (see manual section Dose Weighting).
=> accepting dose accumulation in the tlt file

CHANGES.txt, README.rst, tomo/__init__.py, tomo/objects.py, tomo/viewers/views_tkinter_tree.py
This is my lame attempt (I'm not a UI designer) to improve TS flags. Unfortunately, obj summary does not allow images/icons, only text.. 
- if TS has no alignment, it should not have any labels/flags. Otherwise you would need labels for no ctf, no xxx, no yyy which makes no sense and causes more confusion
- since we can't have any text on hower, a text label nearby is good to have: ⇄ hasAln, ⇲ interp
Also closes #253
=> hide transform matrix column for TS movies; change TS flags

tomo/protocols/protocol_ts_correct_motion.py
- location was wrong
- no need to rely on a counter, as it might fail when dealing with skipped views
=> fix odd-even ti location

tomo/protocols/protocol_ts_base.py
Otherwise the processTiltSeriesStep runs in parallel with convertInputStep, which is wrong
=> fix step deps if no process Ti used

tomo/objects.py
This will allow to replace:
```
for ctfTomoSeries in self.inputSetOfCtfTomoSeries.get():
if tsId == ctfTomoSeries.getTsId():
return ctfTomoSeries
```
with:
```
for item in self.inputSetOfCtfTomoSeries.get().iterItems(where=f"_tsId=='{tsId}'"):
return item
```
I don't see any other method in the tomo objects to get ctftomo by tsId
=> pass kwargs to iterItems of ctf tomo

CHANGES.txt, tomo/__init__.py, tomo/objects.py, tomo/tests/__init__.py, tomo/tests/test_base_centralized_layer.py
Developers:
- Test dataset relion40_sta_tutorial_data expanded.
- TCL: methods for checking sets of TS and TsM improved.
- Class Tomogram method getDim removed as it did not manage heterogeneous sets correctly when iterating (read the
header once, stored it and reused). The Volume method is used now instead, as it reads the size from the file
header for each file.
=>   - TCL expansion and small fixes

tomo/protocols/protocol_ts_correct_motion.py, tomo/viewers/views_tkinter_tree.py
1) renumber TI objIds when restacking (Close #524) *
2) remove output prefix
3) fix angles count
\* I do not know how this may affect acq order or other recent ctf-related code
=> Gs restacking fixes

tomo/protocols/protocol_mesh_from_segmentation.py
Refactored mesh from segmentation protocol to keep track of segmentation labels when the input segmentation is semantic. In addition, the set of meshes was previously assotiated to a SetOfMask, which is incorrect for any practical use case of this object (it should be assotiated to a SetOfTomograms)
=> Refactor mesh from segmentation protocol

tomo/viewers/views_tkinter_tree.py
* Fixing an error displaying the transformation matrix in the tiltseries viewer
=> Fixing an error displaying the transformation matrix in the tiltseries viewer

tomo/objects.py, tomo/protocols/protocol_ts_convert_coords3d.py
Added `score` attribute to the tilt-series coordinate. Also preserving this attribute during conversion to `Coordinate3D`
=> Added score field to tilt series coordinate
